### ISSUE TITLE
[gnome-shell] A few readability improvements

### ISSUE THREAD

**Issue by DarthWound** [LelCP/geeko-gtk-theme#2]
Hello²

1- In overview mode, close button with white on bright green is difficult to see, maybe a dark X would be better? (see image 1)

2- In system status popup, sound selector (and other slides anywhere of course) would be better with a round bullet, it's easier to see and grab than nothing, we have them in GTK themes. (see images 2 & 3)

![geekoimp](https://user-images.githubusercontent.com/1771322/35060926-fbbb5e36-fbbf-11e7-9785-8e532a24ecdc.png)

_PS: don't worry about bigger font size in my shell theme, it's not a bug, I changed from 9pt to 11pt because 9pt is too small for me ;)_

**Comment by LelCP** [comment]
I'm planning to add a few red and blue elements to better address the first part. It will be coming in the next week. As for second part I will see what I can do ;)
